--- 
deployment: 
     tasks: 
          - export DEPLOYPATH=/home/stellmon/public_html/portfolio/birthday-bot/
          - /bin/cp server.js $DEPLOYPATH
          - /bin/cp package.json $DEPLOYPATH
          - /bin/cp -R public $DEPLOYPATH
          - /bin/cp -R views $DEPLOYPATH